### ISSUE TITLE
Create Developers Page

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#12]
Please Create a page for the developers section.

In this section you will need to add a short explanation of developers involve and what tools are been use. 
This page is for sharing in the future. 

Dont forget the SEO information. 

As reference --> https://www.nefrologiaenlinea.com/about/development

**Comment by AlbertLeipzig** [comment]
I need help with SEO

The styling is not complete, but I think we should first change the theme that affects the whole application, and then retouche where it's needed. What do you think?

**Comment by tkalejandro** [comment]
@AlbertLeipzig Yup lets allign another day , it seems today wasnt the day XD
