### ISSUE TITLE
Next js UI

### ISSUE THREAD

**Issue by AlbertLeipzig** [tkalejandro/portfolio-sonia-coronado#15]
- [x] install and configurate [Next.js UI](https://nextui.org/docs/frameworks/nextjs)
- [x] create folder
- [x] document the use of colors

**Comment by tkalejandro** [comment]
@AlbertLeipzig  I kinda tried to quickly do this, but it seems not so simple as I expected. Just to let you know you might need to do a bit of research of how to make it work. Or find whats actually wrong. The official guide didnt work.

**Comment by AlbertLeipzig** [comment]
really? I love good documentation

**Comment by AlbertLeipzig** [comment]
I just installed and wrote the first configuration steps, but failed to bring styles into the project. Maybe we can meet short this week for a brief intro @tkalejandro. Thanks!

anyhow, I tested it a littlbe bit, and next.js UI components can be imported and used

**Comment by AlbertLeipzig** [comment]
btw, Nextjs.UI ask for changing a little bit the provider. It seems to work fine, but nonetheless, please take a look into it

[NextUIProvider](https://nextui.org/docs/frameworks/nextjs#add-provider-to-root)

last but not least, I was not able to find types for this package. An extra package is often needed. Is this an exception?

**Comment by tkalejandro** [comment]
> btw, Nextjs.UI ask for changing a little bit the provider. It seems to work fine, but nonetheless, please take a look into it
> 
> [NextUIProvider](https://nextui.org/docs/frameworks/nextjs#add-provider-to-root)
> 
> last but not least, I was not able to find types for this package. An extra package is often needed. Is this an exception?

I think is already written in TS.
