### ISSUE TITLE
Docs not opening in Windows Local

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#17]
There is a bug happening, when trying to access to Docs via local host, the app is crashing. Maybe is because the unsafe use of `src.doc` 

Environment:

Windows -> Localhost

**Comment by tkalejandro** [comment]
@Hicham2012  Im assigning this to you. I want you to check one more and confirm that is actually not working. I dont have windows machine. 

If is not working probably is something related to the unsafe src.doc that I mentioned.

**Comment by Hicham2012** [comment]
It is working perfectly when I visit `http://localhost:3000/resume`

**Comment by tkalejandro** [comment]
@Hicham2012  not Resume.

http://localhost:3000/docs

and

http://localhost:3000/docs/three/audio.md

For example

**Comment by tkalejandro** [comment]
@AlbertLeipzig  can you try to???   U also have windows :D

**Comment by Hicham2012** [comment]
`http://localhost:3000/docs` is not working for me, it says that docs are undefined.
`http://localhost:3000/docs/three/audio.md` is working perfectly.

**Comment by tkalejandro** [comment]
@Hicham2012  can you solve this ticket ?

**Comment by Hicham2012** [comment]
Sure @tkalejandro , will fix it this week.

**Comment by Hicham2012** [comment]
@tkalejandro what does it show for you when you visit `http://localhost:3000/docs`, can you share a screenshot?

**Comment by tkalejandro** [comment]
<img width="808" alt="Screenshot 2023-11-09 at 07 20 30" src="https://github.com/tkalejandro/portfolio-sonia-coronado/assets/50468778/bf7ab682-04d2-4ee3-8fd1-e27eb89ba7e6">

I think error could be the unsafe src.docs
<img width="852" alt="Screenshot 2023-11-09 at 07 21 20" src="https://github.com/tkalejandro/portfolio-sonia-coronado/assets/50468778/a6eb41e8-3aa3-454a-8d1d-5cef827e21c9">

**Comment by AlbertLeipzig** [comment]
all works fine, but it only does after a browser re-loading or a long time
