### ISSUE TITLE
Create Base MockUp from the 3D World

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#18]
It was disicussed, that the project will be a showcase of things, with the camera navigating when scrolling. 

For this task we need to create each section (Just a box an text for refence).  
You can locate each section in whatever space. (top to bottom) . 
The important is the skeleton of the project.

- Intro
- About
- Projects involve
- Her Music
- Media (conferences)
- Contact

@Hicham2012  Could you please upload your picture here in this ticket as a refence.

**Comment by Hicham2012** [comment]
![Capture d’écran 2023-10-29 174552](https://github.com/tkalejandro/portfolio-sonia-coronado/assets/99765449/b88c8519-84e2-4849-8882-5b35200f3438)
Sure, as you can see in the picture, there will be music notes as particles and a guitar and play button for the welcome section.

**Comment by tkalejandro** [comment]
![Screenshot 2023-11-09 at 20 15 39](https://github.com/tkalejandro/portfolio-sonia-coronado/assets/50468778/5af69c1b-bc63-47ce-98b5-08530a02fb4c)

FINAL PLAN STRATEGY

Welcome Section:

The user starts at the Welcome section, which displays a 3D guitar and a prominent play button.
When the user clicks the play button, a guitar melody or any relevant sound starts playing.
As the sound plays, you can use camera animations to slowly zoom out and fade in the navigation menu (menu items for different sections) at the bottom of the screen.
You can also add subtle ambient lighting changes and particle effects to make the Welcome section visually appealing.

About Section:

When the user clicks on the "About" menu item, the camera transitions smoothly to this section.
Display a 3D model of musical face and provide a brief introduction to the current experience (the sound experience).
In this section, the face can change colors and shape. The user should have the option to change to different moods.
Each mood will connect with music, to the current music happening in the background.
We could fade in text that provides information about her background or the current project.

Projects & Awards Section:

When the user selects "Projects & Awards" from the menu, initiate a camera movement to this section.
Arrange 3D models of her notable projects and awards in a visually appealing way.
Use camera animations to pan or rotate around these models, providing users with a closer look at each project or award.
When you focus on a particular project or award, display relevant text information or sound effects related to it.
When user click on Trophy, project is highlighted.
When user click on project, camara gets closer. 
Audio Library Section:  ( THIS SECTION MIGHT DISSAPEAR)

Transition to the "Audio Library" section using camera movements.
Create a visually striking 3D media player.
User can scroll through music. 
When a user clicks on an audio icon, the sound starts playing, and you can animate the object to move in a fun way, like floating in the air.

Media Cover Section:

For the "Media Cover" section, use a camera movement that zooms in on a newspaper or magazine cover.
When zoomed in, you can provide a 3D rendering (iFrame) of the covers of publications where Sonia has appeared.
Allow users to click on the covers to see more details or read relevant articles.

Contact Section:

Transition to the "Contact" section using camera animations.
Display 3D elements that represent different contact options, like an email icon, phone icon, and social media icons.
When users click on an icon, the camera can zoom in on that specific contact option, providing contact details and links.
Add a visual or audio effect when users interact with the contact options to make it engaging. 
Loader:
Implement a loader animation when the website is initially loaded.
This could be a 3D model spinning or some creative loading animation.
Once loading is complete, transition to the Welcome section.

General Tips:

Use smooth and fluid camera movements and transitions to create a visually pleasing experience.
Consider using lighting effects to highlight and focus on specific elements in each section.
Add subtle particle effects, such as floating musical notes or abstract shapes, to enhance the 3D environment's overall aesthetics.
Ensure that user interactions are intuitive, with clear visual cues and animations to guide the user through the experience.
Provide a way to navigate between sections, like a persistent navigation menu at the bottom of the screen.
Optimize 3D models and textures for performance to ensure a smooth experience.

**Comment by tkalejandro** [comment]
IT was defined.
