### ISSUE TITLE
Navigate camera by scrolling

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#24]
Please create a scrolling navigation that smoothly makes the camara move to each section.

The important at the moment is just to have the functionality. Later on it will be improve depending of final locations and rotations.

**Comment by Hicham2012** [comment]
We can use [ScrollTrigger Gsap](https://gsap.com/docs/v3/Plugins/ScrollTrigger/) library to animate the camera movements while scrolling.

**Comment by tkalejandro** [comment]
@Hicham2012  We can try that. I also see is compatible with React. Feel free to do it. :-) .  

https://gsap.com/resources/React/
