### ISSUE TITLE
Initiate Project and Awards

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#51]
Please create a scene similar to the sketch.

- It should have a floating stand with some awards.
-  Get a generic trophy model. 
- At the background an asymmetrical grid responsive

**Comment by Hicham2012** [comment]
We will need awards references to make them in blender.

**Comment by tkalejandro** [comment]
@Hicham2012  Thats another ticket,  cause thats a lot of work. We dont know the trophies at the moment.
