### ISSUE TITLE
3D Images in Trophys

### ISSUE THREAD

**Issue by tkalejandro** [tkalejandro/portfolio-sonia-coronado#88]
We need to make sure that the Images have a 3D effect once where are moving, this is to show more capabilities of can be done with Three.

**Comment by tkalejandro** [comment]
@Hicham2012  Do you have an idea how to do this.. I think you saw something about it.

**Comment by Hicham2012** [comment]
@tkalejandro , here is the video
[![video](https://github.com/tkalejandro/portfolio-sonia-coronado/assets/99765449/40b0be2a-5200-49ae-8d07-f183fc5693b3)](https://www.youtube.com/watch?v=2W_VR92Pqgs)

**Comment by tkalejandro** [comment]
@Hicham2012  Thank you!!
