### ISSUE TITLE
Interactive Cursor

### ISSUE THREAD

**Issue by Hicham2012** [tkalejandro/portfolio-sonia-coronado#90]
Add a customized cursor that change while hovering on specific elements.

Example: 
When hovering the media elements, cursor will change shape to a circle with instructions in it, which will improve the user experience.
![Capture d’écran 2024-01-11 133536](https://github.com/tkalejandro/portfolio-sonia-coronado/assets/99765449/9e2530a7-4132-401f-84bd-945d39767031)

Note: Better keep this task till all other elements are ready.

**Comment by tkalejandro** [comment]
@Hicham2012  Was this idea the same as this ---> https://github.com/tkalejandro/portfolio-sonia-coronado/pull/115

Or is something else?

**Comment by Hicham2012** [comment]
> @Hicham2012 Was this idea the same as this ---> #115
> 
> Or is something else?

@tkalejandro I added more description to the first comment.

**Comment by tkalejandro** [comment]
@Hicham2012 Thank you!

The only tip I can give you is, make sure whatever you do, it goes mobile first. What happen when is Mobile?? which is 95% of the time . But if you think is not related then all good :D

**Comment by Hicham2012** [comment]
Good point, there will be no cursor in Mobile, so no worries.
